name: Deploy to Amazon ECR

# Trigger on push to main branch
on:
  push:
    branches: ["main"]

env:
  AWS_REGION: us-east-1
  ECR_PUBLIC_REGISTRY: public.ecr.aws
  ECR_REPOSITORY: week4ecr # Replace with your ECR repository name

jobs:
  deploy:
    name: Deploy to ECR
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          IMAGE_NAME: lotsu-daniel-ajayi_anime-app
        run: |
          # Build a docker container and push it to ECR
          docker build -t $ECR_PUBLIC_REGISTRY/$ECR_REPOSITORY:$IMAGE_NAME .
          docker push $ECR_PUBLIC_REGISTRY/$ECR_REPOSITORY:$IMAGE_NAME
          echo "image=$ECR_REGISTRY/$ECR_PUBLIC_REPOSITORY:$IMAGE_NAME" >> $GITHUB_OUTPUT
